-- 1. Create Profiles Table (Users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  email text,
  phone_number text,
  onboarding_step text default 'started',
  role text check (role in ('buyer', 'merchant', 'admin')) default 'buyer',
  avatar_url text,
  business_name text,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  vendor_id uuid references auth.users not null, -- The merchant
  name text not null,
  total_price numeric not null,
  image_url text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Goals Table (User savings for a product)
create table goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- The buyer
  product_id bigint references products not null,
  total_amount numeric not null,
  amount_paid numeric default 0,
  status text check (status in ('saving', 'completed', 'cancelled')) default 'saving',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Transactions Table (Payments towards goals)
create table transactions (
  id bigint generated by default as identity primary key,
  goal_id bigint references goals not null,
  amount numeric not null,
  status text check (status in ('success', 'failed', 'pending')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table products enable row level security;
alter table goals enable row level security;
alter table transactions enable row level security;

-- 6. RLS Policies

-- PROFILES
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- PRODUCTS
create policy "Products are viewable by everyone." on products
  for select using (true);

create policy "Merchants can insert own products." on products
  for insert with check (auth.uid() = vendor_id);

create policy "Merchants can update own products." on products
  for update using (auth.uid() = vendor_id);

-- GOALS
create policy "Users can see own goals." on goals
  for select using (auth.uid() = user_id);

create policy "Merchants can see goals for their products." on goals
  for select using (
    exists (
      select 1 from products
      where products.id = goals.product_id
      and products.vendor_id = auth.uid()
    )
  );

create policy "Users can insert own goals." on goals
  for insert with check (auth.uid() = user_id);

create policy "Users can update own goals." on goals
  for update using (auth.uid() = user_id);

-- TRANSACTIONS
create policy "Users can see own transactions." on transactions
  for select using (
    exists (
      select 1 from goals
      where goals.id = transactions.goal_id
      and goals.user_id = auth.uid()
    )
  );

create policy "Merchants can see transactions for their products." on transactions
  for select using (
    exists (
      select 1 from goals
      join products on products.id = goals.product_id
      where goals.id = transactions.goal_id
      and products.vendor_id = auth.uid()
    )
  );
