/**
 * Database type definitions for Supabase.
 * This file will be auto-generated by Supabase CLI after schema deployment.
 * For now, we define the types manually based on our schema.
 */

export type UserRole = 'buyer' | 'merchant' | 'admin';
export type GoalStatus = 'active' | 'paused' | 'completed' | 'fulfilled' | 'cancelled';
export type TransactionType = 'deposit' | 'allocation' | 'payment' | 'refund' | 'fee' | 'payout';
export type CurrencyCode = 'TZS' | 'USD';
export type PaymentFrequency = 'daily' | 'weekly' | 'monthly';

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string;
                    role: UserRole;
                    full_name: string | null;
                    phone_number: string | null;
                    avatar_url: string | null;
                    business_name: string | null;
                    is_verified: boolean;
                    created_at: string;
                };
                Insert: {
                    id: string;
                    role?: UserRole;
                    full_name?: string | null;
                    phone_number?: string | null;
                    avatar_url?: string | null;
                    business_name?: string | null;
                    is_verified?: boolean;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    role?: UserRole;
                    full_name?: string | null;
                    phone_number?: string | null;
                    avatar_url?: string | null;
                    business_name?: string | null;
                    is_verified?: boolean;
                    created_at?: string;
                };
            };
            products: {
                Row: {
                    id: string;
                    merchant_id: string;
                    title: string;
                    description: string | null;
                    price: number;
                    stock_quantity: number;
                    image_url: string | null;
                    category: string | null;
                    is_active: boolean;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    merchant_id: string;
                    title: string;
                    description?: string | null;
                    price: number;
                    stock_quantity?: number;
                    image_url?: string | null;
                    category?: string | null;
                    is_active?: boolean;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    merchant_id?: string;
                    title?: string;
                    description?: string | null;
                    price?: number;
                    stock_quantity?: number;
                    image_url?: string | null;
                    category?: string | null;
                    is_active?: boolean;
                    created_at?: string;
                };
            };
            goals: {
                Row: {
                    id: string;
                    user_id: string;
                    product_id: string;
                    target_amount: number;
                    current_amount: number;
                    start_date: string;
                    deadline_date: string;
                    payment_frequency: PaymentFrequency;
                    status: GoalStatus;
                    cancellation_fee_snapshot: number;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    product_id: string;
                    target_amount: number;
                    current_amount?: number;
                    start_date?: string;
                    deadline_date: string;
                    payment_frequency: PaymentFrequency;
                    status?: GoalStatus;
                    cancellation_fee_snapshot?: number;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    product_id?: string;
                    target_amount?: number;
                    current_amount?: number;
                    start_date?: string;
                    deadline_date?: string;
                    payment_frequency?: PaymentFrequency;
                    status?: GoalStatus;
                    cancellation_fee_snapshot?: number;
                    created_at?: string;
                };
            };
            wallets: {
                Row: {
                    id: string;
                    user_id: string;
                    currency: CurrencyCode;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    currency?: CurrencyCode;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    currency?: CurrencyCode;
                    created_at?: string;
                };
            };
            ledger_entries: {
                Row: {
                    id: string;
                    wallet_id: string;
                    goal_id: string | null;
                    type: TransactionType;
                    amount: number;
                    description: string | null;
                    reference_id: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    wallet_id: string;
                    goal_id?: string | null;
                    type: TransactionType;
                    amount: number;
                    description?: string | null;
                    reference_id?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    wallet_id?: string;
                    goal_id?: string | null;
                    type?: TransactionType;
                    amount?: number;
                    description?: string | null;
                    reference_id?: string | null;
                    created_at?: string;
                };
            };
        };
        Views: {};
        Functions: {
            get_wallet_balance: {
                Args: { wallet_id_param: string };
                Returns: number;
            };
            process_payment: {
                Args: {
                    goal_id_param: string;
                    amount_param: number;
                    reference_id_param: string;
                };
                Returns: { success: boolean; new_balance: number; is_completed: boolean };
            };
            cancel_goal: {
                Args: { goal_id_param: string };
                Returns: { success: boolean; refund_amount: number; fee_amount: number };
            };
        };
        Enums: {
            user_role: UserRole;
            goal_status: GoalStatus;
            transaction_type: TransactionType;
            currency_code: CurrencyCode;
        };
    };
}

// Convenience types for easier usage
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Product = Database['public']['Tables']['products']['Row'];
export type Goal = Database['public']['Tables']['goals']['Row'];
export type Wallet = Database['public']['Tables']['wallets']['Row'];
export type LedgerEntry = Database['public']['Tables']['ledger_entries']['Row'];
