export const typography = {
  fontFamily: {
    // Gilroy font family variants (Unified brand typography)
    thin: "Gilroy-Regular",
    extraLight: "Gilroy-Regular",
    light: "Gilroy-Regular",
    regular: "Gilroy-Regular",
    medium: "Gilroy-Medium",
    semiBold: "Gilroy-SemiBold",
    bold: "Gilroy-Bold",
    extraBold: "Gilroy-Bold",
    black: "Gilroy-Bold",
    // Italic variants (Fallback to standard weights)
    thinItalic: "Gilroy-Regular",
    extraLightItalic: "Gilroy-Regular",
    lightItalic: "Gilroy-Regular",
    regularItalic: "Gilroy-Regular",
    mediumItalic: "Gilroy-Medium",
    semiBoldItalic: "Gilroy-SemiBold",
    boldItalic: "Gilroy-Bold",
    extraBoldItalic: "Gilroy-Bold",
    blackItalic: "Gilroy-Bold",
  },
  fontSize: {
    xs: 13,
    sm: 15,
    md: 17,
    lg: 19,
    xl: 21,
    xxl: 25,
  },
  lineHeight: {
    xs: 17,
    sm: 21,
    md: 25,
    lg: 29,
    xl: 33,
    xxl: 37,
  },
};
